### PR TITLE
Chore/api updates

### PR DESCRIPTION
**Pull request by thepsalmist**
This PR fixes the requirement to hard wire the Elasticsearch Indices on the config file/ ENV variables. 
Fixes Issue #9

### CODE REVIEW

**Comment by philbudne** [comment]
This isn't something that needs a quick fix (OK with current config until October 2024).

I've put my thoughts about the requirements in issue https://github.com/mediacloud/news-search-api/issues/9 which references the related issue https://github.com/mediacloud/news-search-api/issues/11 that could be addressed at the same time

**Review by pgulley — COMMENTED** [review]
Is this ready to merge?

**Comment by philbudne** [comment]
@pgulley -- No, I commented on a number reasons this PR has a number of issues, which I commented on in #9 

I'll write more below, but wanted to get this out.

**Review by philbudne — COMMENTED** [review]
As I said in the comments, and in #9 this isn't an emergency, but this feels like an emergency fix.

There are more config issues see #11 that also need addressing/cleanup, but are not urgent.

**Pull request closed without merging**
